

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Release Drafter
on:
  workflow_call:
    inputs:
      config-name:
        description: |
          If your workflow requires multiple release-drafter configs it be helpful to override the config-name.
          The config should still be located inside `.github` as that's where we are looking for config files.
        required: false
        type: string
        default: 'release-drafter.yml'
      commits-since:
        description: | 
          A date in ISO format marking the initial commit for the release draft. This is applied only when no prior release is available.
        required: false
        type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# clare all permissions for GITHUB_TOKEN
permissions: {}

jobs:
  detect-version:
    name: Detect version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: 'false'

      - id: has-pom
        run: |
          if [ -f pom.xml ]; then
            echo "status=true" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        if: steps.has-pom.outputs.status == 'true'
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - id: version
        if: steps.has-pom.outputs.status == 'true'
        run: |
          mvn --batch-mode --non-recursive help:evaluate -Dexpression=project.version -Doutput=target/version.txt
          V=$(cat target/version.txt)
          echo "version=${V%-SNAPSHOT}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  update_release_draft:
    name: Update Release Draft
    needs: detect-version
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-latest
    # skip release drafter on next development commits
    if: >
      needs.detect-version.outputs.version != '' &&
      !startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare for next development iteration')

    steps:
      - uses: apache/maven-gh-actions-shared@release-drafter # temporary copy of the release-drafter action
        id: release-drafter
        with:
          config-name: ${{ inputs.config-name }}
          version: ${{ needs.detect-version.outputs.version }}
          commitish: ${{ github.ref }}
          commits-since: ${{ inputs.commits-since }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release drafter status
        if: steps.release-drafter.outputs.id == ''
        run: exit 1

  milestones-managment:
    name: Milestones Management
    needs: detect-version
    permissions:
      # write permission is required to manage milestones
      issues: write
    runs-on: ubuntu-latest
    # execute only on next development commits
    if: >
      needs.detect-version.outputs.version != '' &&
      startsWith(github.event.head_commit.message , '[maven-release-plugin] prepare for next development iteration')

    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          CURRENT_VERSION: ${{ needs.detect-version.outputs.version }}
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const version = process.env.CURRENT_VERSION;
            
            console.log('branch: ' + branch);
            console.log('version: ' + version);
            
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            
            console.log('All open milestones: ');
            console.log(milestones.data);
            
            var milestone;
            if (milestones.data.length > 1) {
              milestone = milestones.data.find(({description}) => description?.includes('branch: ' + branch));
            } else if (milestones.data.length == 1) {
              milestone = milestones.data[0];
            }
            
            console.log('Current milestone: ');
            console.log(milestone);
            
            core.summary.addHeading('Milestone management');
            
            // in first step just create new milestone - closing the old one will be in the next step
            // if something fails here - we don't want to close the existing milestone
            const resultNew = await github.rest.issues.createMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: version,
                description: 'branch: ' + branch
            });
            
            console.log('Created new milestone: ');
            console.log(resultNew.data);
            
            core.summary.addRaw('New milestone: ');
            core.summary.addLink(resultNew.data.title, resultNew.data.html_url);
            core.summary.addBreak();
            
            // now close the existing milestone
            if (milestone) {
              const resultOld = await github.rest.issues.updateMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                milestone_number: milestone.number,
                state: 'closed'
              });
            
              console.log('Closed old milestone: ');
              console.log(resultOld.data);
            
              core.summary.addRaw('Closed milestone: ');
              core.summary.addLink(milestone.title, milestone.html_url);
              core.summary.addBreak();
            } else {
              console.log('No existing milestone to close');
              core.summary.addRaw('No existing milestone to close - please verify');
              core.summary.addBreak();
            }
            
            core.summary.write();
